# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import json
from setuptools import setup

kwargs = json.loads(
    """
{
    "name": "projen-python",
    "python_requires": ">=3.6",
    "author": "Eric Riddoch",
    "author_email": "eric.riddoch@bengroup.com",
    "version": "0.1.0",
    "extras_require": {
        "eric": [
            "boto3"
        ]
    }
}
"""
)

setup(**kwargs)
